name: Pull-request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test Extensions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Compile
        run: |
          mvn clean compile -DskipTests

      - name: Check style
        run: |
          mvn spotless:check

      - name: Run tests
        run: |
          mvn clean test -B 

    
